# Generated by Django 4.2.5 on 2023-12-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schair_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchairDataml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adviceml',
            fields=[
                ('schair_dataml', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schair_app.schairdataml')),
                ('advice_text', models.TextField()),
            ],
        ),
    ]
