# Generated by Django 4.2.5 on 2023-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schair_app', '0002_schairdataml_adviceml'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posture_status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Adviceml',
        ),
        migrations.DeleteModel(
            name='SchairDataml',
        ),
    ]
